// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mczvalghdiuhnkeynmwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jenZhbGdoZGl1aG5rZXlubXd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNDkyNDMsImV4cCI6MjA1MTgyNTI0M30.fH8ocO905Yjo9d8byzH98LTLtn7YxCu-2y-V1HMM-RI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);